version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  to-the-moonfolio.api:
    build:
      context: .
      dockerfile: ./ToTheMoonFolio.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - rabbitmq
  to-the-moonfolio-data-broker.api:
    build:
      context: .
      dockerfile: ./ToTheMoonfolio.DataBroker.Api/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - postgres
      - rabbitmq
  to-the-moonfolio-data-processor:
    build:
      context: .
      dockerfile: ./ToTheMoonfolio.DataProcessor/Dockerfile
    depends_on:
      - postgres
      - rabbitmq